### ISSUE TITLE
魅族机子安卓版本5.1，flyme版本6.0以上，悬浮窗权限申请方法无法使用，导致崩溃

### ISSUE THREAD

**Issue by zzj19921227** [zhaozepeng/FloatWindowPermission#29]
应该是flyme 6.0以上的问题，我这里测试flyme 6.3.0的机子直接崩溃报错，之前没有升级flyme时测试是没问题的，
![1](https://user-images.githubusercontent.com/19340884/35847769-95e69692-0b56-11e8-98f0-a4704245aa93.png)

报错如下图：

**Comment by oncealong** [comment]
魅族 pro6 android:7.1.1 flyme6.2.5.0A 同样crash
===================================
--------- beginning of crash
 E/AndroidRuntime: FATAL EXCEPTION: main
                   Process: com.github.github PID: 12005
                   java.lang.SecurityException: Permission Denial: starting Intent { act=com.meizu.safe.security.SHOW_APPSEC flg=0x10000000 cmp=com.meizu.safe/.security.AppSecActivity (has extras) } from ProcessRecord{3a62010 12005:com.github.github/u0a1008} (pid=12005, uid=11008) not exported from uid 1000
                       at android.os.Parcel.readException(Parcel.java:1684)
                       at android.os.Parcel.readException(Parcel.java:1637)
                       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3491)
                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1526)
                       at android.app.Activity.startActivityForResult(Activity.java:4262)
                       at android.app.Activity.startActivityForResult(Activity.java:4220)
                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
                       at android.app.Activity.startActivity(Activity.java:4594)
                       at android.app.Activity.startActivity(Activity.java:4527)
                       at common.permission.rom.MeizuUtils.applyPermission(MeizuUtils.java:38)
                       at common.permission.FloatWindowManager$3.confirmResult(FloatWindowManager.java:146)
                       at common.permission.FloatWindowManager$8.onClick(FloatWindowManager.java:225)
                       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:171)
                       at android.os.Handler.dispatchMessage(Handler.java:110)
                       at android.os.Looper.loop(Looper.java:203)
                       at android.app.ActivityThread.main(ActivityThread.java:6451)
at java.lang.reflect.Method.invoke(Native Method)
                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by oncealong** [comment]
在最新的魅族flymes 6.2.5 用通用的申请悬浮窗权限即可.
```
    public static void commonROMPermissionApplyInternal(Context context) throws Exception {
        Class clazz = Settings.class;
        Field field = clazz.getDeclaredField("ACTION_MANAGE_OVERLAY_PERMISSION");
        Intent intent = new Intent(field.get(null).toString());
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.setData(Uri.parse("package:" + context.getPackageName()));
        context.startActivity(intent);
    }
```
整体代码如下:
```
    /**
     * 去魅族权限申请页面
     */
    public static void applyPermission(Context context) {
        try {
            Intent intent = new Intent("com.meizu.safe.security.SHOW_APPSEC");
            intent.setClassName("com.meizu.safe", "com.meizu.safe.security.AppSecActivity");
            intent.putExtra("packageName", context.getPackageName());
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(intent);
        } catch (Exception e) {
            try {
                Log.e(TAG, "获取悬浮窗权限, 打开AppSecActivity失败, " + Log.getStackTraceString(e));
                // 最新的魅族flyme 6.2.5 用上述方法获取权限失败, 不过又可以用下述方法获取权限了
                commonROMPermissionApplyInternal(context);
            } catch (Exception eFinal) {
                MiscUtils.showToast("跳转授权窗口失败，请尝试手动开启悬浮窗权限");
                Log.e(TAG, "获取悬浮窗权限失败, 通用获取方法失败, " + Log.getStackTraceString(eFinal));
            }
        }
    }
```

**Comment by oncealong** [comment]
已提交pull request, 代码修改见:
https://github.com/zhaozepeng/FloatWindowPermission/pull/30

**Comment by waynell** [comment]
@oncealong 魅族最新的6.3.0版本连通用的方法也不行了

**Comment by zhaozepeng** [comment]
@oncealong 非常感谢

**Comment by liyuzhao** [comment]
@waynell 魅族最新的6.3.0更简单了，我提pull request了

**Comment by zhaozepeng** [comment]
@waynell OK，通过了，非常感谢
